name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: sudo apt install debootstrap squashfs-tools grub2-common xorriso mtools python3

      - name: Build Process
        run: |
          sudo python3 build.py config.json
       
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: persisos-amd64
          path: output/*.iso
          compression-level: 0
          retention-days: 30
