name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: sudo apt install debootstrap squashfs-tools grub2-common xorriso mtools python3

      - name: Build Process
        run: |
          sudo python3 build.py PersisOS-2.0-amd64.json --workdir build --outdir output

      - name: Upload ISO to the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            output/*.iso
